### ISSUE TITLE
Support for Views

### ISSUE THREAD

**Issue by Cicco0** [ajjahn/puppet-dns#156] opened 2016-03-09 15:18 UTC
I want to integrate the possibility of views in this module. However, it seems to be a bit difficult after several attempts, since the configuration has to be adapted in several places.

I'm able to create a view with the following code:
[Pastebin](http://pastebin.com/N5yGyckw)

but I get, of course, an error message:

> /etc/named.rfc1912.zones:13: when using 'view' statements, all zones must be in views

The cause of the error is in the "named.conf.erb" file that makes an include:

> include "/etc/named.rfc1912.zones";

When a view is used in this module, this include should be included by an view, like as follow:

`view "global" {
  match-clients {
    any;
  }
  include "/etc/named.rfc1912.zones"; 
};`

Is there another way or what solution would you propose?

Andy

**Comment by solarkennedy** [comment] 2016-12-29 16:33
Closing as dupe of #35

**Closed by solarkennedy** 2016-12-29 16:33 UTC
