### ISSUE TITLE
Invalid relationship errors with concat

### ISSUE THREAD

**Issue by ITBlogger** [ajjahn/puppet-dns#81] opened 2015-02-18 00:18 UTC
Hi,

Trying to get the module to work and currently getting errors that look like:

```
Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[/var/opt/lib/pe-puppet/concat/_etc_named_zones_db.lab.<redacted>.com.stage/fragments/9_db.lab.<redacted>.com.ns1,A,lab.<redacted>.com.record] { notify => Exec[concat_/etc/named/zones/db.lab.<redacted>.com.stage] }, because Exec[concat_/etc/named/zones/db.lab.<redacted>.com.stage] doesn't seem to be in the catalog
```

Any ideas on how I can resolve this to get things going?

**Comment by ITBlogger** [comment] 2015-02-18 00:29
It looks like concat requires that the file be present before it can work on it.

```
A minimal example might be:

1
2
3
4
5
6
7
8
9
concat { '/tmp/file':
  ensure => present,
}

concat::fragment { 'tmpfile':
  target  => '/tmp/file',
  content => 'test contents',
  order   => '01'
}
```

**Comment by solarkennedy** [comment] 2015-02-18 04:02
I think this is a dupe of #78. I have some tests to reproduce the issue in #80.
As far as I know we *are* ensuring that the file exists?
https://github.com/ajjahn/puppet-dns/blob/master/manifests/zone.pp#L50

Patches welcome? I'm not super sure what is wrong.

**Comment by ITBlogger** [comment] 2015-02-18 15:13
Yep, I can't figure out what's wrong either. I've tried a number of things to fix it, but so far nothing has worked.

Could possibly be a bug with concat?

**Comment by ITBlogger** [comment] 2015-02-18 15:40
One question I have is if you can define everything all at once or if you need to wait to define records after the initial server install and config has been done?

**Comment by solarkennedy** [comment] 2015-02-18 19:01
I... think it very well might be a bug in concat, especially because the dependency connections that it errors on are "private" concat resources.


No, everything must be defined at once for puppet. The catalog must be compiled in its entirety.

**Comment by ITBlogger** [comment] 2015-02-18 22:43
Made pull request to fix this https://github.com/ajjahn/puppet-dns/pull/84

**Closed** 2015-02-21 04:59 UTC
